springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
